### ISSUE TITLE
Когда уже пива попьем?

### ISSUE THREAD

**Issue by kuza2010** [SedovS/sNotes#1]
Мы уник закончили, а ты че тут сидишь чето коммитишь, рофлишь?!
Гоу 🤪🤡🥂

**Comment by SedovS** [comment]
Диплом сам себя не запушит. 
Вот получим диплом, тогда и можно по бутылочке!

**Comment by kuza2010** [comment]
Будем держать это открытым.

**Comment by kuza2010** [comment]
Думаю можно закрывать. Было жестко.
